export * from "./Logo";
export * from "./Header";
export * from "./Footer";
export * from "./SearchBar";
export * from "./MoviesList";
export * from "./MovieDetails";
export * from "./MovieCard";
export * from "./MovieForm";
export * from "./Genres";
